baseURL: "https://rahuls.com"
languageCode: "en-EN"
defaultContentLanguage: "en"
title: "Rahuls"
summaryLength: 30
RelativeURLs: false
CanonifyURLs: true
enableRobotsTXT: true
enableEmoji: true
paginate: 6
paginatePath: "page"
enableGitInfo: true
pygmentsCodefences: true 
pygmentsUseClasses: true
theme: "rahuls"

params:
  author: "Rahuls"
  site_name: "Rahuls"
  description: "Rahuls Description"
  locale: "en-US"
  type: "website"
  email: 'rahuls@gmail.com'

  social_media:
    facebook_url: "#"
    twitter_url: "#"
    telegram_url: "#"
    linkedin_url: "#"
    whatsapp_url: "https://wa.me/0880044332"


  company:
    - name: 'About'
      url: '#'
    - name: 'Blog'
      url: '#'
  resources:
    - name: 'All Product'
      url: '#'
    - name: 'Documentation'
      url: '#'
  help_and_support:
    - name: 'License'
      url: '#'
    - name: 'Contact'
      url: '#'
  terms:
    - name: 'Terms And Condition'
      url: '#'
    - name: 'Privacvy Policy'
      url: '#'
